### PR TITLE
Add building official Dockerhub image

### PR DESCRIPTION
**Pull request by gdubicki**
Hi!

Thanks for your great tool!

As I wanted to use it in a CI/CD based on Docker so I had to build and push an image to some registry. It's here https://hub.docker.com/r/gdubicki/overtrue-phplint .

However I would prefer to switch to an image built from your repo, under your name - hence the PR.

Apart from merging this PR you would have to just add your Dockerhub credentials to Travis secrets like documented here https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry .

### CODE REVIEW

**Comment by overtrue** [comment]
I have changed this action from travis-ci to github actions https://github.com/overtrue/phplint/actions?query=workflow%3ADocker

**Comment by overtrue** [comment]
https://hub.docker.com/r/overtrue/phplint

**Comment by gdubicki** [comment]
Thanks! I have deleted my image and switched to yours.

**Comment by overtrue** [comment]
@gdubicki OK, you are welcome.

**Pull request merged**
