### PR TITLE
Add support Symfony 6

### PR DESCRIPTION
**Pull request by Myks92**
Issue #117

### CODE REVIEW

**Comment by olegpro** [comment]
@overtrue hello!

Can you release it?

**Comment by olegpro** [comment]
@overtrue hello!

Can you release it?

**Comment by overtrue** [comment]
@olegpro https://github.com/overtrue/phplint/releases/tag/3.1.0

**Comment by overtrue** [comment]
https://github.com/overtrue/phplint/releases/tag/4.1.0

**Comment by olegpro** [comment]
@overtrue thanks :)

**Comment by overtrue** [comment]
@olegpro ❤️

**Pull request merged**
