### PR TITLE
Bug fix on process callback

### PR DESCRIPTION
**Pull request by LTSCommerce**
The process callback property is can be accessed before intialisation which causes a fatal error

This PR fixes that. It is also much better typed by using a `Closure` instead of `mixed`, and it sets the property as nullable with null as default.

Finally I changed the no -op function to a short syntax just because its a lot nicer :)

### CODE REVIEW

**Comment by overtrue** [comment]
Thanks, please resolve the conflicts.

**Comment by LTSCommerce** [comment]
done

**Comment by overtrue** [comment]
Thanks.

**Comment by LTSCommerce** [comment]
np thanks for quick merge :)

**Pull request merged**
